---

plugins:
  - jest

env:
  node: true

parserOptions:
  ecmaVersion: 2020

root: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

rules:
  no-console: 0
  import/extensions: 0
  no-underscore-dangle: 0
